# Generated by Django 4.1.3 on 2022-11-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_book_title_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="title_page",
        ),
        migrations.AddField(
            model_name="book",
            name="title_page_image",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers"),
        ),
    ]
